paths:
  root_path: "experiments"
  output_path: "${paths.root_path}/0325_question_only_qwen_7B.csv"
  
dataset:
  repo_id: "tin-lab/fgqa_hs"

model:
  name: "Qwen/Qwen2-7B" 
  max_model_len: 4096
  language_only: True
  
processing:
  debug: True
  chunk_size: 50 # 2000
  
sampling:
  temperature: 0
  top_p: 1
  max_tokens: 1
  batch_size: 64

data:
  modality: "text"
  add_scene_description: True

  