data:
  add_scene_description: True
  modality: image
  num_unique_images: 2014
dataset:
  repo_id: tin-lab/fgqa_hs
model:
  language_only: true
  max_model_len: 4096
  mm_cache_preprocessor: true
  name: qwen2.5VL
paths:
  output_path: data/behavioral-data/model_outputs/0426_vlm_text_qwen2.5VL.csv
  root_path: data/behavioral-data
processing:
  chunk_size: 500
  debug: false
sampling:
  batch_size: 64
  max_tokens: 1
  temperature: 0
  top_p: 1
