paths:
  image_dir: "/projectnb/tin-lab/yuluq/data/gqa/data/images"
  root_path: "/projectnb/tin-lab/yuluq/data/subset_combined_stats_data/test/"
  csv_path: "${paths.root_path}/output.tsv"
  output_path: "${paths.root_path}/paligemma-3b-base-res.csv"

model:
  name: "google/paligemma-3b-pt-224"
  max_model_len: 4096

sampling:
  temperature: 0.7
  top_p: 0.9
  max_tokens: 10

data:
  num_samples: 2846
  num_unique_images: 10